name: Deploy project to firebase

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "16.x"
      - run: npm install
      - run: npm run build
      - uses: w9jds/firebase-action@v11.22.0
      - run: npm run deploy
        env:
          FIREBASE_TOKEN: 1//0gyPiB2rEuaCJCgYIARAAGBASNgF-L9IrWVb7zih9lqkOXOlxTlLuC2Vj2zF8M6LokBZ5W12SuKBKtdtAlSJXGSN2izVvZxwmSA
